### ISSUE TITLE
Discussion: New UI and A11y WG facilitator

### ISSUE THREAD

**Issue by nainar** [ampproject/wg-ui-and-a11y#17]
As @aghassemi leaves the WG, we need to assign a new WG facilitator. 

There is no process for changing the WG Facilitator in our Governance documentation but I have filed an issue here: https://github.com/ampproject/meta-tsc/issues/16

Creating this issue to do the change in the public.

**Comment by kristoferbaxter** [comment]
Looks like the TSC agrees. [ampproject/meta#39](https://github.com/ampproject/meta/pull/39)

Let's start taking the next steps.

**Comment by nainar** [comment]
I want to propose myself as the new facilitator of the WG. 

My credentials: I work as the PM on the UI Working Group, this means I am often facilitating scoping of components, working with engineers and designers on implementation and tracking the launch of the product.

Happy to field any questions/concerns.

cc @aghassemi who is the outgoing facilitator to facilitate one last issue for the WG.

**Comment by aghassemi** [comment]
@nainar would be a great facilitator for this WG. :100: gets my vote.
