### ISSUE TITLE
Discussion: What is the suggested process to adding members to the UI and A11y WG?

### ISSUE THREAD

**Issue by nainar** [ampproject/wg-ui-and-a11y#19]
Proposed criteria:

The new proposed member should meet the following minimum criteria:
- Person should have some knowledge of components frameworks.
- Demonstrated user advocacy in fields of user experience and a11y.
- Be willing to attend Sprint Planning meetings. Held once every 2 weeks.

The following criteria is good to have:
- Have committed changes to the AMP Project. (If an engineer)
- Have committed a UI component to AMP Project. (If an engineer)
- Be bringing a new perspective to the team. (Design, Performance, a11y)

Updates: Per @andrewwatterson's comment about designers not usually committing code to the project I moved the criteria of committing code to a nice to have and only for engineers.

**Comment by andrewwatterson** [comment]
The UI WG is probably the most likely to have non-engineers as members, so I'd propose removing the commit requirements/focus. Jonathan and Daniel haven't committed changes to AMP, for example, and I barely have. :)

**Comment by nainar** [comment]
Agreed. Made changes inline. How does it look now?

**Comment by nainar** [comment]
New proposal: We accept the TSC's bar: https://github.com/ampproject/meta/blob/8636da774c933acad0733763f657f3aa66c0c916/working-groups/best-practices.md#working-group-membership
