### ISSUE TITLE
wg-ui-and-a11y Status Update 2019-07-22

### ISSUE THREAD

**Issue by cvializ** [ampproject/wg-ui-and-a11y#23]
## What was accomplished

- Talking to devs
- Carousel demo
- LAPIs design thinking
- amp-carousel 0.2, draft PR and tests (1.0?)
- auto lightbox maint
- video: shaka and user activation
- request intercepting
- amp-stories + e2e
- amp stateful page
- responsive amp-soundcloud PR

## Lessons learned

- Minifier and inlining can change performance negatively, esp Terser
- Use Lolex in unit tests (with correct window), not sinon’s useFakeTimers
- Add a lint!

## What's next

- stream-gallery draft PR and tests
- ads and video docking
- amp-fx-collection float-in
- writing first interception e2e tests
- merge E2E interception
- share findings about bfcache for stateful AMP

/cc @ampproject/wg-ui-and-a11y

**Comment by aghassemi** [comment]
Not ramping up loaders? :cry:

**Comment by nainar** [comment]
@aghassemi Just waiting on finishing up the last few bits of stream-gallery

@sparhami @andrewwatterson FYI
